name: MobCount
main: net.raidstone.core.Count
version: 1.0.0

commands:
  countmobs:
    usage: /countmob <radius>
    description: Counts mobs in a defined radius
  entityremove:
    usage: /entityremove <type> [radius]
    description: Removes entities